version: 2

formats:
  - pdf
  - epub
  - htmlzip

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"

sphinx:
  configuration: ForDocumentation/docs/conf.py

python:
  install:
    - method: pip
      path: .
    - requirements: ForDocumentation/requirements.txt
