version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"

sphinx:
  configuration: ForDocumentation/docs/conf.py

python:
  install:
    - method: pip
      path: .

# Optional: if you need extra dependencies
#  requirements_file: requirements.txt
